ТЗ 12
griatva/java-filmorate pull request #3
Opened 2024-12-13 16:37 UTC by griatva

2024-12-14 13:05 UTC, tomattman requested changes
Привет, комментарии в коде, да и кажется по условию, должна быть картинка со схемой базы данных

2024-12-14 13:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LinkedHashSet<Genre> genres;
не стоит для типа переменной выбирать такие классы, для таких случаев чаще всего тип выбирают по интерфейсу, т.е. не должно быть повторений, тогда лучше сделать Set могут быть повторения - LIst ключ значение - Map

2024-12-14 13:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer likes;
учитывая что ты хранишь только число, может сложиться ситуация, что один пользователь просто бесконечно ставит лайки одному фильму, для таких случаев обычно используется связь, многие ко многим, и связываем с таблицей пользователей, и если пользователь поставили лайк, то его запись становится связана с записью фильма

2024-12-14 13:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public boolean equals(Object o) {
вообще у ломбука есть аннотация и при ее использовании equals и hashCode генерируются автоматически

2024-12-14 13:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer likes;
посмотрел, в базе вроде как все нормально, но из-за того что модель выглядит так, получать эти данные чуть сложнее

2024-12-14 13:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/JdbcFilmRepository.java
> +            public Optional<Film> extractData(ResultSet rs) throws SQLException {
у тебя будет дублирование кода в каждом методе, стоит вынести это в отдельный класс или в отдельный метод и переиспользовать его множество раз

2024-12-14 13:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/genre/JdbcGenreRepository.java
> +            public List<Genre> extractData(ResultSet rs) throws SQLException {
аналогично, думаю, в остальных классах будет так же, этот комментарий повторять не буду

2024-12-14 13:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +        filmRepository.addLike(filmId, userId);
тут бы проверку сделать, что лайка еще нету

2024-12-14 13:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +        filmRepository.deleteLike(filmId, userId);
да и тут бы проверку тоже, хотя тут уже не обязательно

2024-12-16 12:49 UTC, griatva commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +        filmRepository.addLike(filmId, userId);
ок, я ее сделаю, но вообще у меня при запросе в БД, если уже есть такая строка, но ничего не поменяется. То есть дважды точно не добавиться - при конфликте ничего не произойдет. Я думала, что этого достаточно.

2024-12-17 13:29 UTC, griatva commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/JdbcFilmRepository.java
> +            public Optional<Film> extractData(ResultSet rs) throws SQLException {
Повторяющиеся части (извлечение фильма и добавление жанров) я выделила в отдельные методы, но логика обработки этих данных разная (в одном случае нужно получить один фильм, во втором лист фильмов, а в третьем вообще нужна обработка через два запроса и мапу), поэтому весь метод extractData() я не стала выделять в отдельный метод. Так будет корректно?

2024-12-17 13:30 UTC, griatva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer likes;
Правильно ли я поняла, что тут все в порядке? Корректно оставить так?

2024-12-18 11:49 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer likes;
на уровне этого задания, да, это больше как рекомендация на будущее

2024-12-18 11:59 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/JdbcFilmRepository.java
> +            public Optional<Film> extractData(ResultSet rs) throws SQLException {
Чаще всего такие действия лушче вынести в отдельный метод или класс просто для читаемости
сейчас у тебя в этом методе следуюшая структура 
сначала длинная строка с запросом
потом вызов основного метода, в котором используется анонимный класс, с перегурзкой одного метода, и из-за такой структуры метода, в нем чуть тяжелее разобраться
а если бы былоа следующая структура как мне кажется было бы гораздо легче разобраться

private final static String FIND_BY_ID_QUERY = "QUERY";

public Optional<Film> findFilmById(long id) {
return jdbc.query(FIND_BY_ID_QUERY , new SingleFilmExtractor());
}

т.е. структура метода, из длинной переменной и запутанных вложенностей превращается в вызов одного метода с параметрами (SingleFilmExtractor это отдельный класс с переопределыннм маппингом)
и в текущем виде все правильно, просто так чуть легче воспринимается 
Ну и кончено же все зависит от проекта и команды,  в некоторыех, скажут что тот способ которым сделано единтсвенные правильный

2024-12-18 12:01 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +        filmRepository.addLike(filmId, userId);
да достаточно, но снова все зависит от специцикаций и архитектуры
в одном случае, если сделано неправильное действие но оно не значительно, то это просто игнорируется 
во втором случае это может считаться критической ошибкой, которую надо залогировать, где то сохранить, и/или показать пользователю что он сделал что-то не так

2024-12-18 12:02 UTC, tomattman approved these changes
Привет, отличная работа, но коментарии я поотвечал, там все в основном по разным подходам, поэтому ничего критичного

2025-01-08 13:51 UTC, merged